nohup: 忽略输入
mkdir: 无法创建目录 “outputs_august”: 文件已存在
wandb: Currently logged in as: anaiis (for-graduate-anaiis). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.17.7 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.17.0
wandb: Run data is saved locally in /data/Anaiis/anti_overfit/wandb/run-20240824_203249-ukpupknh
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run azure-thunder-2
wandb: ⭐️ View project at https://wandb.ai/for-graduate-anaiis/0824-deap-noshuf
wandb: 🚀 View run at https://wandb.ai/for-graduate-anaiis/0824-deap-noshuf/runs/ukpupknh
wandb: - 0.010 MB of 0.010 MB uploadedwandb: \ 0.010 MB of 0.010 MB uploadedwandb: | 0.010 MB of 0.010 MB uploadedwandb: / 0.010 MB of 0.010 MB uploadedwandb: - 0.010 MB of 0.010 MB uploadedwandb: \ 0.010 MB of 0.010 MB uploadedwandb: | 0.010 MB of 0.010 MB uploadedwandb: / 0.017 MB of 0.033 MB uploaded (0.004 MB deduped)wandb: - 0.017 MB of 0.033 MB uploaded (0.004 MB deduped)wandb: \ 0.033 MB of 0.033 MB uploaded (0.004 MB deduped)wandb: 🚀 View run azure-thunder-2 at: https://wandb.ai/for-graduate-anaiis/0824-deap-noshuf/runs/ukpupknh
wandb: ⭐️ View project at: https://wandb.ai/for-graduate-anaiis/0824-deap-noshuf
wandb: Synced 6 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20240824_203249-ukpupknh/logs
Traceback (most recent call last):
  File "watch_PE.py", line 79, in <module>
    constructed = construct_graphs(args.data, args.dataset, args.window_length, args.strides)
  File "/data/Anaiis/anti_overfit/Effect_Att/utils.py", line 60, in construct_graphs
    all_samples = np.load(os.path.join(dataset_dir + 'data.npy'))
  File "/home/micro/anaconda3/envs/bob_env1/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/data/Anaiis/Effect_Att/Data/len_96/False/data.npy'
Traceback (most recent call last):
  File "watch_PE.py", line 79, in <module>
    constructed = construct_graphs(args.data, args.dataset, args.window_length, args.strides)
  File "/data/Anaiis/anti_overfit/Effect_Att/utils.py", line 60, in construct_graphs
    all_samples = np.load(os.path.join(dataset_dir + 'data.npy'))
  File "/home/micro/anaconda3/envs/bob_env1/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/data/Anaiis/Effect_Att/Data/len_96/False/data.npy'
Error processing False
